import {
  AlertTriangle,
  ArrowLeftRight,
  ArrowRight,
  Banknote,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  ClipboardPenLine,
  Command,
  CreditCard,
  File,
  FileText,
  HandCoins,
  HelpCircle,
  Image,
  LayoutDashboard,
  LogIn,
  LogOut,
  type LucideIcon,
  Moon,
  MoreVertical,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  User2Icon,
  Users2,
  X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  add: Plus,
  arrowRight: ArrowRight,
  billing: CreditCard,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  close: X,
  dashboard: LayoutDashboard,
  ellipsis: MoreVertical,
  help: HelpCircle,
  kanban: CircuitBoardIcon,
  logo: Command,
  login: LogIn,
  logout: LogOut,
  media: Image,
  moon: Moon,
  page: File,
  pinjaman: ArrowLeftRight,
  post: FileText,
  profile: User2Icon,
  projects: ClipboardPenLine,
  project: HandCoins,
  saldo: Banknote,
  settings: Settings,
  sun: SunMedium,
  trash: Trash,
  user: User,
  users: Users2,
  warning: AlertTriangle,
};
